version: 0.2

phases:
  install:
    
    commands:
      - echo Installing Node
      - curl -sL https://deb.nodesource.com/setup_15.x | bash -
      - apt update
    #  - apt install nodejs npm
   #   - nodejs --version
    
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      #- npm install
      
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the react-Node code
      #- cd my-app
      #- npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
     files:
        - '**/*'
